version: '3.8'

services:
  app:
    build:
      context: .
      target: development
    volumes:
      - .:/app
    ports:
      - "12300:12300"
    env_file:
      - .env.local
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
      - PORT=12300
    tty: true
    stdin_open: true
    # command: sh
    command: npm run dev
