version: '3.8'

services:
  app:
    build:
      context: .
      target: development
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    env_file:
      - .env.local
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
    tty: true
    stdin_open: true
    # command: sh
    command: npm run dev
